spring:
  application:
    name: spm
  datasource:
    url: jdbc:mysql://localhost:3306/shopdb  # 데이터베이스 URL
    username: root  # 데이터베이스 사용자 이름
    password: 1234  # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스 이름 (다른 데이터베이스는 적절한 드라이버 클래스를 사용)
  jpa:
    hibernate:
      ddl-auto: update  # 스키마 자동 업데이트 (none, update, create, create-drop)
    show-sql: true  # SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리를 포맷하여 출력
        jdbc:
          time_zone: UTC  # JDBC의 시간대 설정
jwt:
  secret: GkLf28hBrtykPdzKmMCiO5w+QwKctBQzql8rV0BMy4s=